# Generated by Django 2.0.6 on 2019-09-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.FloatField(max_length=10, null=True)),
                ('latitude', models.FloatField(max_length=50, null=True)),
                ('longitude', models.FloatField(max_length=50, null=True)),
                ('deviceImeiNo', models.IntegerField(max_length=15, null=True)),
                ('plateNumber', models.IntegerField(max_length=10, null=True)),
                ('AssetCode', models.IntegerField(max_length=10, null=True)),
                ('speed', models.IntegerField(max_length=5, null=True)),
                ('companyId', models.CharField(max_length=10, null=True)),
                ('engine', models.CharField(max_length=50, null=True)),
                ('assetId', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
