# Generated by Django 2.0.6 on 2019-09-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicles',
            new_name='vehicle',
        ),
    ]
