# Generated by Django 2.0.6 on 2019-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190909_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='AssetCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plateNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
