# Generated by Django 2.0.6 on 2019-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20190909_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='deviceImeiNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
