# Generated by Django 2.0.6 on 2019-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20190909_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
