# Generated by Django 2.0.6 on 2019-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
