# Generated by Django 2.0.6 on 2019-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddevice',
            name='Device_Model',
            field=models.CharField(choices=[('P', 'Prime 07'), ('B', 'Benley 140'), ('O', 'OBDII'), ('R', 'Optimus 2.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='Driver_Name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='IMEI_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='Sim_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='Vehicle_Licence_No',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='Vehicle_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Company_address',
            field=models.CharField(max_length=50),
        ),
    ]
