# Generated by Django 2.0.6 on 2019-09-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_auth', '0002_auto_20190903_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Company_address',
            field=models.CharField(default='Sholinganallur', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Company_name',
            field=models.CharField(default='Amigait technology', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(default='9677691904', max_length=10),
        ),
    ]
