# Generated by Django 2.0.6 on 2019-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_auto_20190907_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='Vehile_Type',
            field=models.CharField(choices=[('A', 'Ambulance'), ('M', 'Motorcycle'), ('B', 'Bus'), ('C', 'Car'), ('M', 'Minivan'), ('T', 'Tempo'), ('T', 'Truck')], max_length=20, null=True),
        ),
    ]
