# Generated by Django 2.0.6 on 2019-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_adddevice_vehile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Active_Devices',
            field=models.CharField(default='180', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='Inactive_Devices',
            field=models.CharField(default='20', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='No_of_Vehicles',
            field=models.CharField(default='256', max_length=3),
        ),
    ]
